project:
  type: website
  output-dir: docs
  # post-render:
  #   - "cp -rnv static/. _site" # source: https://github.com/quarto-dev/quarto-cli/discussions/4162#discussioncomment-4831352

website:
  title: "Ian Hoppe"
  site-url: https://irhoppe.github.io
  description: "Ecologist and naturalist applying quantitative analytical tools to understand and conserve wildlife."
  favicon: https://res.cloudinary.com/sternula/image/upload/v1696498427/pbfw-m_dtqo8y.svg
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    logo: assets/ian/img/pbfw-m.svg
    tools:
    - icon: github
      href: https://www.github.com/irhoppe/irhoppe.github.io
    right:
      - text: Projects
        aria-label: "Projects"
        href: projects/index.qmd
      - text: About
        aria-label: "About Me"
        href: about/index.qmd
      - text: CV
        aria-label: "CV"
        href: cv/index.qmd
  
  page-footer:  
    left: >-
     &#169; 2024 Ian Hoppe
    center: |
      <a class="link-dark me-1" href="https://github.com/irhoppe" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://au.linkedin.com/in/ian-hoppe-65ab93b0" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0000-0001-6482-2386" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.com/citations?user=mENVqBsAAAAJ" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>

    right: 
      - text: "Contact"
        aria-label: "Contact Form"
        href: "contact.qmd"
      
format: 
  html:
    theme:
      light:
        - cosmo
        - assets/theme-light.scss
        - assets/colors-light.scss
        - assets/fonts.scss
      dark: 
        - cosmo
        - assets/theme-dark.scss
        - assets/colors-dark.scss
        - assets/fonts.scss
    # highlight-style:
    #   light: assets/silvia/a11y-light.theme
    #   dark: assets/silvia/a11y-dark.theme
    code-link: true
    email-obfuscation: javascript
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute: 
  freeze: auto

# include-in-header: assets/silvia/umami.html
